[package]
name = "quickcheck_macros"
version = "0.1.2"
authors = ["Andrew Gallant <jamslam@gmail.com>"]

[lib]
name = "quickcheck_macros"
path = "src/lib.rs"
plugin = true

[dependencies.quickcheck]
path = ".."
